### ISSUE TITLE
Path mismatch of Sensetime Dataset

### ISSUE THREAD

**Issue by andrea-pilzer** [AaltoML/vio_benchmark#39]
Hi,

Thank you for the great codebase, I am running tests with hybvio_runner on Sensetime dataset and I had a path error.
I fixed it by changing the path where I save the dataset from `data/benchmark/sensetime` to `data/benchmark`, this way it is consistent with `compare_to_others.py` [here](https://github.com/AaltoML/vio_benchmark/blob/297c916bb4e9fb94e614fdb3b44adc686720e9b2/hybvio_runner/compare_to_others.py#L53). 

Maybe to avoid this minor issue in the future you could add in the description for converting Sensetime [here](https://github.com/AaltoML/vio_benchmark/blob/297c916bb4e9fb94e614fdb3b44adc686720e9b2/convert/sensetime_to_benchmark.py#L20) to copy the processed folders back to benchmark folder? I am not sure if this will mess up the code but I felt it was good to report it.

Best, Andrea

**Comment by pekkaran** [comment]
Hello,
Thanks for the report, I merged a PR #40 that I think fixes the issue, please let me know if it doesn't. The dataset handling in this project is unfortunately quite messy, being aimed at more general use than this open source project really requires.

I tried following the [SenseTime conversion](https://github.com/AaltoML/vio_benchmark/blob/main/convert/sensetime_to_benchmark.py#L7-L20) instructions to the letter, and it seems to me they result in correct paths. The resulting processed data should be in a hierarchy like `vio_benchmark/data/benchmark/sensetime/A0/data.jsonl`.

The problem however was that the file `sensetime-a.json` that [this line](https://github.com/AaltoML/vio_benchmark/blob/main/hybvio_runner/compare_to_others.py#L134) refers to, defining the full paths, seemed to be missing. It should have shown error `Exception: Benchmark set sensetime-a not found`. In the fix PR I added the missing file, also similarly for the TUM dataset, which should fix the issue without moving any dataset folders.
